import { parseTypography, pxToNumber } from '../token-model.mjs';

const entries = (model, type) => model.byType[type] ?? [];
const record = (tokens, mapper = (token) => token.light) =>
  Object.fromEntries(tokens.map((token) => [token.key, mapper(token)]));
const js = (value) => JSON.stringify(value, null, 2);
const variableName = (name) => `--cd-${name}`;

function sizeMap(model) {
  const output = record(entries(model, 'size'));
  const density = new Map(entries(model, 'density').map((token) => [token.key, token]));

  if (density.has('control-height')) {
    output.control = `var(${variableName('density-control-height')})`;
  }
  if (density.has('control-height-lg')) {
    output['control-lg'] = `var(${variableName('density-control-height-lg')})`;
  }
  if (entries(model, 'platform').some((token) => token.key === 'touch-min')) {
    output['touch-min'] = `var(${variableName('platform-touch-min')})`;
  }

  return output;
}

export function createTailwindPreset(model, banner = 'Tailwind') {
  const colors = record(
    entries(model, 'color'),
    (token) => `var(${variableName(token.name)})`,
  );
  const fontSize = {};

  for (const token of entries(model, 'typography')) {
    const value = parseTypography(token.light);
    if (value.fontSize === undefined) continue;
    fontSize[token.key] = [
      `${value.fontSize}px`,
      {
        lineHeight: `${value.lineHeight}px`,
        fontWeight: String(value.fontWeight),
      },
    ];
  }

  const sizes = sizeMap(model);
  const preset = {
    darkMode: 'class',
    theme: {
      extend: {
        colors,
        spacing: record(entries(model, 'spacing')),
        borderRadius: record(entries(model, 'radius')),
        width: sizes,
        height: sizes,
        minWidth: sizes,
        minHeight: sizes,
        fontSize,
        fontWeight: record(entries(model, 'fontWeight'), (token) => String(token.light)),
        lineHeight: record(entries(model, 'lineHeight')),
        boxShadow: record(entries(model, 'shadow')),
      },
    },
  };

  return `'use strict';\n\n// Generated Com Design ${banner} preset. Do not edit by hand.\nmodule.exports = ${js(preset)};\n`;
}

function cssLines(tokens, mode = 'light') {
  return tokens
    .map(
      (token) =>
        `  ${variableName(token.name)}: ${mode === 'dark' ? token.dark : token.light};`,
    )
    .join('\n');
}

function scopeLines(scope, prefixes) {
  return Object.entries(scope)
    .filter(([name]) => prefixes.some((prefix) => name.startsWith(prefix)))
    .map(([name, value]) => `  ${variableName(name)}: ${value};`)
    .join('\n');
}

function themeChangedLines(model, theme, mode = 'light') {
  const baseMode = mode === 'dark' ? 'dark' : 'light';
  return entries(model, 'color')
    .filter(
      (token) =>
        theme[mode]?.[token.name] !== undefined &&
        theme[mode][token.name] !== token[baseMode],
    )
    .map((token) => `  ${variableName(token.name)}: ${theme[mode][token.name]};`)
    .join('\n');
}

function themeCssBlocks(model) {
  return Object.values(model.themes ?? {})
    .map((theme) => {
      const light = themeChangedLines(model, theme, 'light');
      const dark = themeChangedLines(model, theme, 'dark');
      return `${theme.selector},\n${theme.dataSelector} {\n${light}\n}\n\n.dark${theme.selector},\n.dark ${theme.selector},\n.dark${theme.dataSelector},\n.dark ${theme.dataSelector} {\n${dark}\n}`;
    })
    .join('\n\n');
}

export function createThemeCss(model) {
  const dynamic = [
    ...entries(model, 'color'),
    ...entries(model, 'density'),
    ...entries(model, 'platform'),
  ];
  const dark = dynamic.filter((token) => token.hasDarkOverride);
  const comfortable = scopeLines(model.scopes.densityComfortable, ['density-']);
  const android = scopeLines(model.scopes.platformAndroid, ['platform-']);
  const themes = themeCssBlocks(model);

  return `/* Generated by Com Design. Do not edit by hand. */\n:root {\n${cssLines(dynamic)}\n}\n\n.dark {\n${cssLines(dark, 'dark')}\n}\n\n${themes}${themes ? '\n\n' : ''}.density-comfortable {\n${comfortable}\n}\n\n.platform-android {\n${android}\n}\n`;
}

function numericRecord(tokens) {
  return record(tokens, (token) => pxToNumber(token.light));
}

function scopeRecord(scope, prefix) {
  return Object.fromEntries(
    Object.entries(scope)
      .filter(([name]) => name.startsWith(prefix))
      .map(([name, value]) => [name.slice(prefix.length), pxToNumber(value)]),
  );
}

function themeColorRecord(model, theme, mode) {
  return Object.fromEntries(
    entries(model, 'color').map((token) => [
      token.key,
      theme[mode]?.[token.name] ?? (mode === 'dark' ? token.dark : token.light),
    ]),
  );
}

export function createReactNativeTokens(model) {
  const typography = {};
  for (const token of entries(model, 'typography')) {
    typography[token.key] = parseTypography(token.light);
  }

  const compact = numericRecord(entries(model, 'density'));
  const comfortable = {
    ...compact,
    ...scopeRecord(model.scopes.densityComfortable, 'density-'),
  };
  const platformTouch = entries(model, 'platform').find(
    (token) => token.key === 'touch-min',
  );
  const themes = Object.fromEntries(
    Object.entries(model.themes ?? {}).map(([key, theme]) => [
      key,
      {
        name: theme.name,
        color: {
          light: themeColorRecord(model, theme, 'light'),
          dark: themeColorRecord(model, theme, 'dark'),
        },
      },
    ]),
  );

  const output = {
    color: {
      light: record(entries(model, 'color')),
      dark: record(entries(model, 'color'), (token) => token.dark),
    },
    themes,
    space: numericRecord(entries(model, 'spacing')),
    radius: numericRecord(entries(model, 'radius')),
    size: numericRecord(entries(model, 'size')),
    density: {
      compact,
      comfortable,
    },
    platform: {
      ios: { touchMin: pxToNumber(platformTouch?.light) },
      android: {
        touchMin: pxToNumber(
          model.scopes.platformAndroid['platform-touch-min'] ?? platformTouch?.light,
        ),
      },
    },
    fontSize: numericRecord(entries(model, 'fontSize')),
    lineHeight: numericRecord(entries(model, 'lineHeight')),
    fontWeight: record(entries(model, 'fontWeight'), (token) => Number(token.light)),
    typography,
    shadow: {
      light: record(entries(model, 'shadow')),
      dark: record(entries(model, 'shadow'), (token) => token.dark),
    },
    motion: record(entries(model, 'motion')),
  };

  return `// Generated by Com Design. Do not edit by hand.\n// Source px values map 1:1 to React Native density-independent layout numbers.\nexport const tokens = ${js(output)} as const;\n\nexport type ComDesignTokens = typeof tokens;\n`;
}

export function createBuildManifest(model) {
  return (
    js({
      schemaVersion: 1,
      source: 'design-source/colors_and_type.css',
      sourceHash: model.sourceHash,
      targets: ['tailwind', 'nativewind', 'react-native', 'mcp'],
      tokenCount: model.consumer.length,
      themes: Object.values(model.themes ?? {}).map((theme) => theme.name),
    }) + '\n'
  );
}
